
services:
  postgres:
    image: postgres:latest
    container_name: PostgresContainer
    environment:
      POSTGRES_DB: customerdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 271024
    ports:
      - "5432:5432"

  springbootapp:
    image: app # Replace with your actual Spring Boot image
    build: .
    depends_on:
      - postgres
    ports:
      - "8080"
    deploy:
      replicas: 3
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/customerdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 271024